[[mgr.append_keymap]]
on  = ["c", "s"]
run = "plugin steam"

[[mgr.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd /home/tapo4eg3d/.steam/steam/steamapps/common"
desc = "Go to the Steam folder (storage)"

[[mgr.prepend_keymap]]
on = ["i"]
run = ["toggle_all", "toggle", "remove --force"]

[[mgr.prepend_keymap]]
on   = [ "<C-n>" ]
run  = '''
    shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''
desc = "Drag and Drop"
