return {
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   version = false,
  --   build = ":TSUpdate",
  --   event = {
  --     "BufReadPost",
  --     "BufNewFile",
  --   },
  --   opts = {
  --     highlight = {
  --       enable = true,
  --       additional_vim_regex_highlighting = false,
  --     },
  --     indent = {
  --       enable = true,
  --     },
  --     ensure_installed = {
  --       "c",
  --       "lua",
  --       "bash",
  --       "python",
  --       "html",
  --       "javascript",
  --       "typescript",
  --       "rust",
  --       "yaml",
  --       "markdown",
  --     },
  --   },
  --   config = function(_, opts)
  --     require("nvim-treesitter.configs").setup(opts)
  --   end
  -- },

  -- -- Playground allows to inspect the tree built by the Treesitter
  -- {
  --   'nvim-treesitter/playground',
  --   cmd = 'TSPlaygroundToggle',
  -- },
}
